/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class pjmedia_codec_param_setting {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pjmedia_codec_param_setting(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pjmedia_codec_param_setting obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      pjsuaJNI.delete_pjmedia_codec_param_setting(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setFrm_per_pkt(short value) {
    pjsuaJNI.pjmedia_codec_param_setting_frm_per_pkt_set(swigCPtr, this, value);
  }

  public short getFrm_per_pkt() {
    return pjsuaJNI.pjmedia_codec_param_setting_frm_per_pkt_get(swigCPtr, this);
  }

  public void setVad(long value) {
    pjsuaJNI.pjmedia_codec_param_setting_vad_set(swigCPtr, this, value);
  }

  public long getVad() {
    return pjsuaJNI.pjmedia_codec_param_setting_vad_get(swigCPtr, this);
  }

  public void setCng(long value) {
    pjsuaJNI.pjmedia_codec_param_setting_cng_set(swigCPtr, this, value);
  }

  public long getCng() {
    return pjsuaJNI.pjmedia_codec_param_setting_cng_get(swigCPtr, this);
  }

  public void setPenh(long value) {
    pjsuaJNI.pjmedia_codec_param_setting_penh_set(swigCPtr, this, value);
  }

  public long getPenh() {
    return pjsuaJNI.pjmedia_codec_param_setting_penh_get(swigCPtr, this);
  }

  public void setPlc(long value) {
    pjsuaJNI.pjmedia_codec_param_setting_plc_set(swigCPtr, this, value);
  }

  public long getPlc() {
    return pjsuaJNI.pjmedia_codec_param_setting_plc_get(swigCPtr, this);
  }

  public void setReserved(long value) {
    pjsuaJNI.pjmedia_codec_param_setting_reserved_set(swigCPtr, this, value);
  }

  public long getReserved() {
    return pjsuaJNI.pjmedia_codec_param_setting_reserved_get(swigCPtr, this);
  }

  public void setEnc_fmtp(SWIGTYPE_p_pjmedia_codec_fmtp value) {
    pjsuaJNI.pjmedia_codec_param_setting_enc_fmtp_set(swigCPtr, this, SWIGTYPE_p_pjmedia_codec_fmtp.getCPtr(value));
  }

  public SWIGTYPE_p_pjmedia_codec_fmtp getEnc_fmtp() {
    return new SWIGTYPE_p_pjmedia_codec_fmtp(pjsuaJNI.pjmedia_codec_param_setting_enc_fmtp_get(swigCPtr, this), true);
  }

  public void setDec_fmtp(SWIGTYPE_p_pjmedia_codec_fmtp value) {
    pjsuaJNI.pjmedia_codec_param_setting_dec_fmtp_set(swigCPtr, this, SWIGTYPE_p_pjmedia_codec_fmtp.getCPtr(value));
  }

  public SWIGTYPE_p_pjmedia_codec_fmtp getDec_fmtp() {
    return new SWIGTYPE_p_pjmedia_codec_fmtp(pjsuaJNI.pjmedia_codec_param_setting_dec_fmtp_get(swigCPtr, this), true);
  }

  public pjmedia_codec_param_setting() {
    this(pjsuaJNI.new_pjmedia_codec_param_setting(), true);
  }

}
