/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class pjmedia_tone_digit_map {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pjmedia_tone_digit_map(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pjmedia_tone_digit_map obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      pjsuaJNI.delete_pjmedia_tone_digit_map(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setCount(long value) {
    pjsuaJNI.pjmedia_tone_digit_map_count_set(swigCPtr, this, value);
  }

  public long getCount() {
    return pjsuaJNI.pjmedia_tone_digit_map_count_get(swigCPtr, this);
  }

  public pjmedia_tone_digit_map_digits getDigits() {
    long cPtr = pjsuaJNI.pjmedia_tone_digit_map_digits_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pjmedia_tone_digit_map_digits(cPtr, false);
  }

  public pjmedia_tone_digit_map() {
    this(pjsuaJNI.new_pjmedia_tone_digit_map(), true);
  }

}
