/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class pjmedia_tone_digit {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pjmedia_tone_digit(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pjmedia_tone_digit obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      pjsuaJNI.delete_pjmedia_tone_digit(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setDigit(char value) {
    pjsuaJNI.pjmedia_tone_digit_digit_set(swigCPtr, this, value);
  }

  public char getDigit() {
    return pjsuaJNI.pjmedia_tone_digit_digit_get(swigCPtr, this);
  }

  public void setOn_msec(short value) {
    pjsuaJNI.pjmedia_tone_digit_on_msec_set(swigCPtr, this, value);
  }

  public short getOn_msec() {
    return pjsuaJNI.pjmedia_tone_digit_on_msec_get(swigCPtr, this);
  }

  public void setOff_msec(short value) {
    pjsuaJNI.pjmedia_tone_digit_off_msec_set(swigCPtr, this, value);
  }

  public short getOff_msec() {
    return pjsuaJNI.pjmedia_tone_digit_off_msec_get(swigCPtr, this);
  }

  public void setVolume(short value) {
    pjsuaJNI.pjmedia_tone_digit_volume_set(swigCPtr, this, value);
  }

  public short getVolume() {
    return pjsuaJNI.pjmedia_tone_digit_volume_get(swigCPtr, this);
  }

  public pjmedia_tone_digit() {
    this(pjsuaJNI.new_pjmedia_tone_digit(), true);
  }

}
