/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public enum pjsip_hdr_e {
  PJSIP_H_ACCEPT,
  PJSIP_H_ACCEPT_ENCODING_UNIMP,
  PJSIP_H_ACCEPT_LANGUAGE_UNIMP,
  PJSIP_H_ALERT_INFO_UNIMP,
  PJSIP_H_ALLOW,
  PJSIP_H_AUTHENTICATION_INFO_UNIMP,
  PJSIP_H_AUTHORIZATION,
  PJSIP_H_CALL_ID,
  PJSIP_H_CALL_INFO_UNIMP,
  PJSIP_H_CONTACT,
  PJSIP_H_CONTENT_DISPOSITION_UNIMP,
  PJSIP_H_CONTENT_ENCODING_UNIMP,
  PJSIP_H_CONTENT_LANGUAGE_UNIMP,
  PJSIP_H_CONTENT_LENGTH,
  PJSIP_H_CONTENT_TYPE,
  PJSIP_H_CSEQ,
  PJSIP_H_DATE_UNIMP,
  PJSIP_H_ERROR_INFO_UNIMP,
  PJSIP_H_EXPIRES,
  PJSIP_H_FROM,
  PJSIP_H_IN_REPLY_TO_UNIMP,
  PJSIP_H_MAX_FORWARDS,
  PJSIP_H_MIME_VERSION_UNIMP,
  PJSIP_H_MIN_EXPIRES,
  PJSIP_H_ORGANIZATION_UNIMP,
  PJSIP_H_PRIORITY_UNIMP,
  PJSIP_H_PROXY_AUTHENTICATE,
  PJSIP_H_PROXY_AUTHORIZATION,
  PJSIP_H_PROXY_REQUIRE_UNIMP,
  PJSIP_H_RECORD_ROUTE,
  PJSIP_H_REPLY_TO_UNIMP,
  PJSIP_H_REQUIRE,
  PJSIP_H_RETRY_AFTER,
  PJSIP_H_ROUTE,
  PJSIP_H_SERVER_UNIMP,
  PJSIP_H_SUBJECT_UNIMP,
  PJSIP_H_SUPPORTED,
  PJSIP_H_TIMESTAMP_UNIMP,
  PJSIP_H_TO,
  PJSIP_H_UNSUPPORTED,
  PJSIP_H_USER_AGENT_UNIMP,
  PJSIP_H_VIA,
  PJSIP_H_WARNING_UNIMP,
  PJSIP_H_WWW_AUTHENTICATE,
  PJSIP_H_OTHER;

  public final int swigValue() {
    return swigValue;
  }

  public static pjsip_hdr_e swigToEnum(int swigValue) {
    pjsip_hdr_e[] swigValues = pjsip_hdr_e.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (pjsip_hdr_e swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + pjsip_hdr_e.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private pjsip_hdr_e() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private pjsip_hdr_e(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private pjsip_hdr_e(pjsip_hdr_e swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

