/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class pjsua_msg_data {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pjsua_msg_data(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pjsua_msg_data obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      pjsuaJNI.delete_pjsua_msg_data(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setHdr_list(pjsip_hdr value) {
    pjsuaJNI.pjsua_msg_data_hdr_list_set(swigCPtr, this, pjsip_hdr.getCPtr(value), value);
  }

  public pjsip_hdr getHdr_list() {
    long cPtr = pjsuaJNI.pjsua_msg_data_hdr_list_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pjsip_hdr(cPtr, false);
  }

  public void setContent_type(pj_str_t value) {
    pjsuaJNI.pjsua_msg_data_content_type_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getContent_type() {
    long cPtr = pjsuaJNI.pjsua_msg_data_content_type_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setMsg_body(pj_str_t value) {
    pjsuaJNI.pjsua_msg_data_msg_body_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getMsg_body() {
    long cPtr = pjsuaJNI.pjsua_msg_data_msg_body_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public pjsua_msg_data() {
    this(pjsuaJNI.new_pjsua_msg_data(), true);
  }

}
