/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class SWIGTYPE_p_f_pj_status_t_p_char_pj_size_t__pj_str_t {
  private long swigCPtr;

  protected SWIGTYPE_p_f_pj_status_t_p_char_pj_size_t__pj_str_t(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_f_pj_status_t_p_char_pj_size_t__pj_str_t() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_f_pj_status_t_p_char_pj_size_t__pj_str_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

