/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class pjsip_hdr_vptr {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pjsip_hdr_vptr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pjsip_hdr_vptr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      pjsuaJNI.delete_pjsip_hdr_vptr(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setClone(SWIGTYPE_p_f_p_pj_pool_t_p_q_const__void__p_void value) {
    pjsuaJNI.pjsip_hdr_vptr_clone_set(swigCPtr, this, SWIGTYPE_p_f_p_pj_pool_t_p_q_const__void__p_void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_pj_pool_t_p_q_const__void__p_void getClone() {
    long cPtr = pjsuaJNI.pjsip_hdr_vptr_clone_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_pj_pool_t_p_q_const__void__p_void(cPtr, false);
  }

  public void setShallow_clone(SWIGTYPE_p_f_p_pj_pool_t_p_q_const__void__p_void value) {
    pjsuaJNI.pjsip_hdr_vptr_shallow_clone_set(swigCPtr, this, SWIGTYPE_p_f_p_pj_pool_t_p_q_const__void__p_void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_pj_pool_t_p_q_const__void__p_void getShallow_clone() {
    long cPtr = pjsuaJNI.pjsip_hdr_vptr_shallow_clone_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_pj_pool_t_p_q_const__void__p_void(cPtr, false);
  }

  public void setPrint_on(SWIGTYPE_p_f_p_void_p_char_size_t__int value) {
    pjsuaJNI.pjsip_hdr_vptr_print_on_set(swigCPtr, this, SWIGTYPE_p_f_p_void_p_char_size_t__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_p_char_size_t__int getPrint_on() {
    long cPtr = pjsuaJNI.pjsip_hdr_vptr_print_on_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_p_char_size_t__int(cPtr, false);
  }

  public pjsip_hdr_vptr() {
    this(pjsuaJNI.new_pjsip_hdr_vptr(), true);
  }

}
