/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public class pjsip_hdr {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected pjsip_hdr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(pjsip_hdr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      pjsuaJNI.delete_pjsip_hdr(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setType(pjsip_hdr_e value) {
    pjsuaJNI.pjsip_hdr_type_set(swigCPtr, this, value.swigValue());
  }

  public pjsip_hdr_e getType() {
    return pjsip_hdr_e.swigToEnum(pjsuaJNI.pjsip_hdr_type_get(swigCPtr, this));
  }

  public void setName(pj_str_t value) {
    pjsuaJNI.pjsip_hdr_name_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getName() {
    long cPtr = pjsuaJNI.pjsip_hdr_name_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setSname(pj_str_t value) {
    pjsuaJNI.pjsip_hdr_sname_set(swigCPtr, this, pj_str_t.getCPtr(value), value);
  }

  public pj_str_t getSname() {
    long cPtr = pjsuaJNI.pjsip_hdr_sname_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pj_str_t(cPtr, false);
  }

  public void setVptr(pjsip_hdr_vptr value) {
    pjsuaJNI.pjsip_hdr_vptr_set(swigCPtr, this, pjsip_hdr_vptr.getCPtr(value), value);
  }

  public pjsip_hdr_vptr getVptr() {
    long cPtr = pjsuaJNI.pjsip_hdr_vptr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pjsip_hdr_vptr(cPtr, false);
  }

  public pjsip_hdr() {
    this(pjsuaJNI.new_pjsip_hdr(), true);
  }

}
