/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua;

public interface pjsuaConstants {
  public final static int PJ_THREAD_DESC_SIZE = pjsuaJNI.PJ_THREAD_DESC_SIZE_get();
  public final static pjsua_callback WRAPPER_CALLBACK_STRUCT = new pjsua_callback(pjsuaJNI.WRAPPER_CALLBACK_STRUCT_get(), false);
  public final static int PJ_SUCCESS = pjsuaJNI.PJ_SUCCESS_get();
  public final static int PJ_TRUE = pjsuaJNI.PJ_TRUE_get();
  public final static int PJ_FALSE = pjsuaJNI.PJ_FALSE_get();
  public final static int PJSUA_INVALID_ID = pjsuaJNI.PJSUA_INVALID_ID_get();
  public final static int PJSUA_ACC_MAX_PROXIES = pjsuaJNI.PJSUA_ACC_MAX_PROXIES_get();
  public final static int PJSUA_MAX_ACC = pjsuaJNI.PJSUA_MAX_ACC_get();
  public final static int PJSUA_REG_INTERVAL = pjsuaJNI.PJSUA_REG_INTERVAL_get();
  public final static int PJSUA_PUBLISH_EXPIRATION = pjsuaJNI.PJSUA_PUBLISH_EXPIRATION_get();
  public final static int PJSUA_DEFAULT_ACC_PRIORITY = pjsuaJNI.PJSUA_DEFAULT_ACC_PRIORITY_get();
  public final static String PJSUA_SECURE_SCHEME = pjsuaJNI.PJSUA_SECURE_SCHEME_get();
  public final static int PJSUA_MAX_CALLS = pjsuaJNI.PJSUA_MAX_CALLS_get();
  public final static int PJSUA_XFER_NO_REQUIRE_REPLACES = pjsuaJNI.PJSUA_XFER_NO_REQUIRE_REPLACES_get();
  public final static int PJSUA_MAX_BUDDIES = pjsuaJNI.PJSUA_MAX_BUDDIES_get();
  public final static int PJSUA_PRES_TIMER = pjsuaJNI.PJSUA_PRES_TIMER_get();
  public final static int PJSUA_MAX_CONF_PORTS = pjsuaJNI.PJSUA_MAX_CONF_PORTS_get();
  public final static int PJSUA_DEFAULT_CLOCK_RATE = pjsuaJNI.PJSUA_DEFAULT_CLOCK_RATE_get();
  public final static int PJSUA_DEFAULT_AUDIO_FRAME_PTIME = pjsuaJNI.PJSUA_DEFAULT_AUDIO_FRAME_PTIME_get();
  public final static int PJSUA_DEFAULT_CODEC_QUALITY = pjsuaJNI.PJSUA_DEFAULT_CODEC_QUALITY_get();
  public final static int PJSUA_DEFAULT_ILBC_MODE = pjsuaJNI.PJSUA_DEFAULT_ILBC_MODE_get();
  public final static int PJSUA_DEFAULT_EC_TAIL_LEN = pjsuaJNI.PJSUA_DEFAULT_EC_TAIL_LEN_get();
  public final static int PJSUA_MAX_PLAYERS = pjsuaJNI.PJSUA_MAX_PLAYERS_get();
  public final static int PJSUA_MAX_RECORDERS = pjsuaJNI.PJSUA_MAX_RECORDERS_get();
  public final static int PJ_ERR_MSG_SIZE = pjsuaJNI.PJ_ERR_MSG_SIZE_get();
  public final static int PJ_ERRNO_START = pjsuaJNI.PJ_ERRNO_START_get();
  public final static int PJ_ERRNO_SPACE_SIZE = pjsuaJNI.PJ_ERRNO_SPACE_SIZE_get();
  public final static int PJ_ERRNO_START_STATUS = pjsuaJNI.PJ_ERRNO_START_STATUS_get();
  public final static int PJ_ERRNO_START_SYS = pjsuaJNI.PJ_ERRNO_START_SYS_get();
  public final static int PJ_ERRNO_START_USER = pjsuaJNI.PJ_ERRNO_START_USER_get();
  public final static int PJMEDIA_TONEGEN_LOOP = pjsuaJNI.PJMEDIA_TONEGEN_LOOP_get();
  public final static int PJMEDIA_TONEGEN_NO_LOCK = pjsuaJNI.PJMEDIA_TONEGEN_NO_LOCK_get();

}
